language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
script:
   - py.test --cov geobricks_common_test/core/geobricks_common_test.py --cov-report term-missing
